### ISSUE TITLE
Routes into Routes file

### ISSUE THREAD

**Issue by apaganobeleno** [gernest/utron#3]
@gernest First of all thanks for such a great tool, **utron** looks very nice, i really appreciate finding this kind of tool that makes things easier.

I've been talking with one of my teammates about the routes inside utron and wanted to know if it sounds reasonable for you to move the routes to a separate file and apply the routes by reading a routes configuration file.

One of the good thing is that in utron Controller the Routes attribute is a slice, which means we could read these from a JSON/YAML/TOML source file.

Thoughts on this ?

**Comment by gernest** [comment]
@apaganobeleno tThanks for the positive feedback, and for taking your time to discuess `utron`. I did have thought on this, that is why you I used a `[]string` as you have noticed. But I ditched the idea due to the following issues

### naming ?
There will be a need to explicity add the Controller's name  in the `routes` file  and I couldn't fthink of a better way to do that.

What I mean  is with a Route inside an `Example`  controller I can define route like `get,post;/hello/{world};Hello` since I can already deduct `Example` name.

I know there is a way to better do it, and I'm open to suggestion.

### where to put the file?
I was also not so sure where to add the file, take for instance the example `todo` app has 5 directories. so adding 6 directories sounds uncool

### what name to use for the the file?
ofc ouse `routes.{{something}}` but hey, `utron` second premise talks about not assuming stuffs, want to make an exception?

Pulling this Routes out of the Controller won't be hard and wont break anything, but untill we come into consesus about the above issues. That way, we will still make `utron` cool for you and your teammate.

NOTE: `utron` hasn't been released yet, so there are many rooms for improvement for the first version, and I count on good people like you to make it happen.

**Comment by apaganobeleno** [comment]
@gernest regarding the naming i agree with you that this will be a downside, we will need to explicitly add the controller name thats kind of the trade-of we would made, i was thinking that we could have one routes.{json|yaml|toml} inside the config folder, that eliminates the need of another folder.

I hope i can contribute to this feature and other views if needed, if you want and after your approval i would like to implement it, or help implementing it, but for now lets continue de discussion around routes. :wink:

**Comment by gernest** [comment]
@apaganobeleno You are right( about making hard calls) , since we havent released yet it wont be too bad to change the API.

Wish there were some other people to say what they think about this. 

Regarding putting routes in `config` folder doesn't that sound confusing for you. I amean is routes.json a configuration file or?

You got me thnking, maybe it makes sense routes file to be there since we are configuring our routing by the way.
